sudo: required
services:
  - docker

before_install:
  - docker build -t seanmoynihan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true seanmoynihan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "dockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-862233127900"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"